#:kivy 2.1.0
#:import ToolbarScreen toolbarscreen

<ToolbarScreen>:
    MDBoxLayout:
        orientation: 'vertical'
        MDTopAppBar:
            title: root.title
            pos_hint: {'top':1.0}
            elevation: "4dp"
            left_action_items: root.action_items
        MDBoxLayout:
            id: container
            orientation: 'vertical'
            padding: "4dp"
            spacing: "4dp"